

dev:
    @echo "Starting development server..."
    poetry run uvicorn server:app --reload

openapi:
    @echo "Generating OpenAPI schema..."
    poetry run python src/generate_openapi.py
    (cd ../client && yarn generate)
    